/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.barash_serbest_5220505051;

import java.awt.Color;
/**
 *
 * @author const
 */
public class frmButonKontrolPaneli extends javax.swing.JFrame {

    /**
     * Creates new form frmButonKontrolPaneli
     */
    public frmButonKontrolPaneli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simge1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simge2");
        jButton2.setPreferredSize(new java.awt.Dimension(81, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Simge3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Simge4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Simge5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Simge6");
        jButton6.setPreferredSize(new java.awt.Dimension(72, 23));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Simge7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Simge8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Simge9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Simge10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Simge11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Simge12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Simge13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Simge14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Simge15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Simge16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Buton1 için uygulanan fonksiyonlar:        
        renkDegistir(jButton1);        
        butonKontrol(jButton1); 
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 1");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton1 (Simge1) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Buton2 için uygulanan fonksiyonlar:
        renkDegistir(jButton2);
        butonKontrol(jButton2);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 2");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton2 (Simge2) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Buton3 için uygulanan fonksiyonlar:
        renkDegistir(jButton3);
        butonKontrol(jButton3);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 3");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton3 (Simge3) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Buton4 için uygulanan fonksiyonlar:
        renkDegistir(jButton4);
        butonKontrol(jButton4);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 4");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton4 (Simge4) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Buton5 için uygulanan fonksiyonlar:
        renkDegistir(jButton5);
        butonKontrol(jButton5);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 5");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton5 (Simge5) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Buton6 için uygulanan fonksiyonlar:
        renkDegistir(jButton6);
        butonKontrol(jButton6);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 6");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton6 (Simge6) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Buton7 için uygulanan fonksiyonlar:
        renkDegistir(jButton7);
        butonKontrol(jButton7);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 7");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton7 (Simge7) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Buton8 için uygulanan fonksiyonlar:
        renkDegistir(jButton8);
        butonKontrol(jButton8);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 8");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton8 (Simge8) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // Buton9 için uygulanan fonksiyonlar:
        renkDegistir(jButton9);
        butonKontrol(jButton9);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 9");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton9 (Simge9) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // Buton10 için uygulanan fonksiyonlar:
        renkDegistir(jButton10);
        butonKontrol(jButton10);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 10");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton10 (Simge10) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Buton11 için uygulanan fonksiyonlar:
        renkDegistir(jButton11);
        butonKontrol(jButton11);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 11");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton11 (Simge11) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Buton12 için uygulanan fonksiyonlar:
        renkDegistir(jButton12);
        butonKontrol(jButton12);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 12");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton12 (Simge12) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // Buton13 için uygulanan fonksiyonlar:
        renkDegistir(jButton13);
        butonKontrol(jButton13);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 13");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton13 (Simge13) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // Buton14 için uygulanan fonksiyonlar:
        renkDegistir(jButton14);
        butonKontrol(jButton14);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 14");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton14 (Simge14) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // Buton15 için uygulanan fonksiyonlar:
        renkDegistir(jButton15);
        butonKontrol(jButton15);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 15");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton15 (Simge15) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // Buton16 için uygulanan fonksiyonlar:
        renkDegistir(jButton16);
        butonKontrol(jButton16);
        // GraphQL işlemlerini uygulayabilmek için GraphQLButton sınıfından bir nesne oluşturuluyor.               
        GraphQLButton graphqlButton = new GraphQLButton("Button 16");    
        // GraphQL özelliklerini ayarlama 
        graphqlButton.setGraphqlEndpoint("https://example.com/graphql");
        graphqlButton.setGraphqlInfo("JButton16 (Simge16) için GraphQL isteği gerçekleştirildi.");
        // GraphQL isteğini gerçekleştirme 
        graphqlButton.performGraphqlRequest();
    }//GEN-LAST:event_jButton16ActionPerformed
    // Eğer bir butona ilk defa basılıyorsa buton "aktif renk" ve "aktif simge" olacak.
    public void renkDegistir(javax.swing.JButton buton){
        if (buton.getBackground().equals(Color.white)) {
            buton.setBackground(Color.blue);
            buton.setForeground(Color.red);
            /* Butona tıklandığında buton simgesini "aktif simge" durumuna getiriyor.            
            buton.setIcon("com\mycompany\barash_serbest_5220505051\aktifSimge.png");*/
        } 
        else {
            buton.setBackground(Color.white);
            buton.setForeground(Color.white);
            /* Butona daha önce tıklanmışsa buton simgesini "pasif simge" durumuna getiriyor. 
            buton.setIcon("com\mycompany\barash_serbest_5220505051\pasifSimge.png")
            */
        }
    }
    // Eğer basılan butona tekrar basılırsa basılan buton haricinde tüm butonlar "pasif renk" ve "pasif simge" olacak.
    public void butonKontrol(javax.swing.JButton buton){         
        if(buton.getBackground().equals(Color.white)){
            jButton1.setBackground(Color.white); jButton2.setBackground(Color.white); jButton3.setBackground(Color.white); jButton4.setBackground(Color.white);
            jButton5.setBackground(Color.white); jButton6.setBackground(Color.white); jButton7.setBackground(Color.white); jButton8.setBackground(Color.white);
            jButton9.setBackground(Color.white); jButton10.setBackground(Color.white); jButton11.setBackground(Color.white); jButton12.setBackground(Color.white);
            jButton13.setBackground(Color.white); jButton14.setBackground(Color.white); jButton15.setBackground(Color.white); jButton16.setBackground(Color.white);
            
            jButton1.setForeground(Color.white); jButton2.setForeground(Color.white); jButton3.setForeground(Color.white); jButton4.setForeground(Color.white);
            jButton5.setForeground(Color.white); jButton6.setForeground(Color.white); jButton7.setForeground(Color.white); jButton8.setForeground(Color.white);
            jButton9.setForeground(Color.white); jButton10.setForeground(Color.white); jButton11.setForeground(Color.white); jButton12.setForeground(Color.white);
            jButton13.setForeground(Color.white); jButton14.setForeground(Color.white); jButton15.setForeground(Color.white); jButton16.setForeground(Color.white);
            buton.setBackground(Color.blue);
            buton.setForeground(Color.red);
        }
    }
    
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
